language: csharp
mono: none
sudo: false
dotnet: 2.2
dist: xenial


script:
  - dotnet build -c Release
  - dotnet test  -c Release --no-build
  - dotnet pack  -c Release --no-build -p:NoWarn=NU5105


deploy:


  - on:
      branch: master
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
    skip_cleanup: true


  - on:
      branch: develop
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://www.myget.org/F/nettopologysuite/api/v2/package -k $MYGET_API_KEY
    skip_cleanup: true

env:
  global:
  - secure: TlParCZtb2gRNKOt6eg06PhPPk2r1ENU5VZekccU7T93Mcw1eXbKXvMJMom03N3C5uYUey/Xh8fpPwAX416AysV2RDbVwJi85TfJZxnY8S0NRrdq+vmr2WGa8lEE28KA5G+dwm63E86BPepeSmThqAx7+l4ACMhMNdnHF5XhJgHYBxHl/iR69eIhnZAJFMor4RNM/e8u1BtLYYjKL3rN+kNkKZhpT0ohaTr2hyjCH/n2XH9WadjyLwq+umSjC0QKybU1anU600ymume+nbVoKzP9MrUPqiBodlG9lCOSgtEd7tE6EQYK5MqdP3miGRCisYZeKv0NXvywfxfBuDOrsiz8E64QxUJInGOynOJhj+Ag9VKS4HjqQXgPyJnENIahpEiMnOrbMGtmeci96RyVRThv2xACkp/WlMub5NIK9SxJ0dV0GUe5RMvVmWZ0KhfHNBvMkgHey8nTY8ATdMxall6gVnlrRYP0ZxE3Kxcggt5m2z8grV1gMK4oSf6gfOF/kSUbzmNKr9YKxv+Dwz1Ob35Q7ooExz05gE6GOeylxv9PggDMpj+5n/5qjeI9A6fKwtqoqR9k1tmpiClU2EartNjfLc2Yb6lRMrvwOCwA5dqdN6ngm5huS/Eke56Zk4g8LCkyiulqYuakvUUV9mIb+XGfzLGFJBXt1YDGUv77WbA=
  - secure: aEINUS64kaqRxKcCJej9xnNe3WZXhjpsmEH7IRiy2RCK5yLwgYdM60vmQCIZdC5AeUQbW+0ZrOWAVbMxF8e2l0v03nAq83QLpFpqsvEuutNtUTfS5jizP1XMdzkv9EwwrqV/Hx/CTRn0T1eal8ziYD2yIJsCMhzYUY91Mi1lZMC+RnrLT3q30FmzGvu3zW1fE6ZVWOfU2Zi/fZP3d6uRt1xku3cCvbiXT4F4H9Lr8ZjEjgU2tK1LIczY65qzDzt+KandyL+QbRu5nRdRNa0JUe1PsHpAluuYqlkcwAnXnN3/uOe+IcSSJvBRCzo74xWsCO5AiH8Abdj7M1rjsWY4l6FJ+UoY6Ci2PVFWKyJ7tsqmKu9zfRBoDEwsGZWJLqu6JdeK3LI029CGEi8s5U55adQARxqEJb/klJ6EJfMdOlsPoEvFWZKWDGIHKkKbQR4PZgJu7U9IMZNQmb/DKtvF1g2Ks99zcPsnTwVekNznmLomK8rzD9AfbbQmxOJRzr06N9krjCb96Yo3JCE08s/Nw63c2vbRyVJQlB/nfmPkH6j/YzbmfKlgt+jRMHONkvdNcJT7sUaYn4BnrbEsnJAOleOpfI95APx8eh1RwpZlE3peFN6PiIKQ8SDhht7WNcja0v6yWfry+8cBSlGfmfo3jEqt9VVMVVSwfvUctNxIzzg=
