language: csharp
mono: none
sudo: false
dotnet: 2.1.403
dist: trusty
script:
- bash ./travis-build.sh
env:
  global:
    secure: WbTpyCsfztSl74qaG9TZbBxyOplAM4aeT9BEZ+EJW6Z88meNFJSzbkzL7PqKIwZgInhJIN6WsV3tTUn+7DcdZt6MaUpUpm2d2dUOFq66bnuDBZSAwudi93gBqTJjn2OK3cCUMr2BZdj2AJYwGXdeColQ6IvqmPplDnoBA5JDlVQqWuepxTYNF9pCFs+Qcw/LglXknlzNccJluK0R6zSh9TVJOWwBE2UAH93Oa6IQWjGDyM+j7VQ1oIsqOfddWoNoAVYRdMoxO5Y/BUSNWZft1jkrtWjw5FywCNWOLG9jlal23Gtk7+3Nyx6dk8oB2Oir6N9qogW1ta8hKgSMutCPnaLbBw/U815mkrCBXA1iDkNXLm/Oi9JJjasQ0aHuklRLzqdSz1IrCkWj6AzEIpbaDjUYI9ZMDaHFG2PQgZvDQfY3NQGIootik5THJPd46SEa6q3MjZct5Tr6Ou6+oCwT+n7qRZl9shi901VH59i0F4CYpAEkCPO70iJEbELiVx2MWC41gqQAzJW7AQ/oVO4pVI2gkPx+FnoVRemLtp4if3kZ2ilIUqHYNrymnl/pq2hKZk53cAjYtCuuWbYduaYAhNbxmG6tQ8VQexmZEWpWXE//6P8sd612rtf2CbBKzUWfZ96Pykldr2+DSf7aMaR6LFW9HsIDiJgXDAzlM+rVW+I=
